#ifndef ERRORTYPE_H
#define ERRORTYPE_H

#define ENSEMBLE_SUCCESS                ( 0)

#define ENSEMBLE_ERROR_INVALID_MEMORY	(-103)
#define ENSEMBLE_ERROR_SOCKET_CONNECT	(-100)
#define ENSEMBLE_ERROR_SOCKET_READ		(-101)
#define ENSEMBLE_ERROR_SOCKET_WRITE		(-102)
#define ENSEMBLE_ERROR_ALREADY_CONNECT  (-104)
#define ENSEMBLE_ERROR_NO_CONNECT       (-105)
#define ENSEMBLE_ERROR_SOCKET_READ_EOF  (-106)


#define ENSEMBLE_CONNECT_CONTROL_PORT      0x01

#endif
